name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      # run steps automatically include the correct working dir
      run:
        working-directory: zmk-glove80
    steps:
      # Checkout the common repo instead of the local one
      - name: Checkout zmk-stuff
        uses: actions/checkout@v4
        with:
          repository: J-MR-T/zmk-stuff
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout ZMK source
        uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: zmk-glove80/src
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v14
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Inject shared zmk-stuff context for Nix
        run: |
          # Copy all regular files from the parent (zmk-stuff) into config/shared/
          # This handles shared.h, or any future .dtsi/.h files you add.
          mkdir -p config/shared \;
          find .. -maxdepth 1 -type f -exec cp {} config/shared/ \;
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: glove80.uf2
          path: zmk-glove80/glove80.uf2 # not a run action, so specify path explicitly
